---
- name: Get releases info from API
  uri:
    url: '{{ nodejs_index_json_url }}'
    method: GET
    return_content: yes
  delegate_to: localhost
  register: nodejs_index

- name: Get latest lts or current version
  when: (nodejs_major_version == 'lts' or nodejs_major_version == 'current')
  vars:
    query_feature_version:
      # "[?lts != `false`].version | [0]"
      "[?{{ nodejs_major_version }} != `false`].version | [0]"
  block:
    - set_fact:
        nodejs_full_version_fact: "{{ nodejs_index.json | json_query(query_feature_version) | replace('v', '') }}"
    - set_fact:
        nodejs_major_version_fact: "{{ nodejs_full_version_fact.split('.')[0] }}"

# https://github.com/ansible/ansible/issues/27299#issuecomment-331068246
# https://stackoverflow.com/a/44547305/5430535
- name: Get latest custom version
  when: not (nodejs_major_version == 'lts' or nodejs_major_version == 'current')
  vars:
    query_feature_version:
      "[?contains(version, 'v{{ nodejs_major_version }}')].version | [0]"
  block:
    - set_fact:
        nodejs_full_version_fact: "{{ nodejs_index.json | to_json | from_json | json_query(query_feature_version) | replace('v', '') }}"
    - set_fact:
        nodejs_major_version_fact: "{{ nodejs_full_version_fact.split('.')[0] }}"

- name: Get download link 4 Windows
  when:
    - ansible_os_family == 'Windows'
    - ansible_env.PROCESSOR_ARCHITECTURE == 'AMD64'
  vars:
    nodejs_direct_url_win_10_default: https://nodejs.org/dist/v{{ nodejs_full_version_fact }}/node-v{{ nodejs_full_version_fact }}-x64.msi
    nodejs_direct_url_win_7_default: https://nodejs.org/dist/v12.19.0/node-v12.19.0-x64.msi
  block:
    - set_fact:
        nodejs_direct_download_url_win_fact: "{{ nodejs_direct_url_win | default(nodejs_direct_url_win_10_default) }}"
      when: ansible_distribution_major_version == '10'
    # https://github.com/nodejs/node/pull/31954
    - set_fact:
        nodejs_direct_download_url_win_fact: "{{ nodejs_direct_url_win | default(nodejs_direct_url_win_7_default) }}"
        nodejs_full_version_fact: 12.19.0
      when: ansible_distribution_major_version == '6'

# - name: Set fact about NodeJS output file after download
#   when: ansible_os_family == 'Windows'
#   set_fact:
#     nodejs_installer_file_fact: "{{ nodejs_direct_download_url_win_fact | urlsplit('path') | basename }}"

# - pause:
#     echo: yes
